name: marp-build
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Marp Build
        uses: docker://marpteam/marp-cli:v2.2.2
        with:
          args: slide-deck.md -o slides/index.html
        env:
          MARP_USER: root:root
      

      - name: Setup git Config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Push Slides
        run: |
          git add slides
          git commit -m "Build Slides"
          git push origin main
