name: marp-build
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make slides folder
        run: mkdir slides

      - name: Marp Build
        uses: docker://marpteam/marp-cli:v2.2.2
        with:
          args: slide-deck.md -o slides/index.html
        env:
          MARP_USER: root:root
